### ISSUE TITLE
Question: Why does my app always say there's an update? 

### ISSUE THREAD

**Issue by ccnokes** [electron/windows-installer#101]
App versions:
Electron 0.37.8
Packaged with electron-builder 3.19.0
electron-winstaller-fixed version 2.5.0 (the sub-dependency that electron-builder relies on)
Windows 10

When I run my app it constantly says it needs an update. Looking at the SquirrelSetup.log, it looks like there's a few issues: 
1. It says my local app's version is greater than the update server's version in the RELEASES file. Both are 0.4.7 though. The RELEASES file looks like: `E866AD98009AA8837FDE4E692FC30E2633B33453 MyApp-0.4.7-ia32-full.nupkg 45917992`. My app's package.json version: `0.4.7`
2. It downloads the update, "fixes up tray icons" which causes the desktop shortcut to break. When I inspect it's Properties, the "Target" field isn't present. When it's working, it looks like: `C:\Users\IEUser\AppData\Local\MyApp\Update.exe --processStart "MyApp.exe"`.
3. If I restart the app, the same thing happens again and again.

Let me know if you need more details. I'm not sure if this an issue with my implementation, or what but any help you can offer would be greatly appreciated 😸 . 

My SquirrelSetup.log:
```
2016-06-02 10:37:48> Program: Starting Squirrel Updater: --processStart MyApp.exe
2016-06-02 10:37:48> Program: Want to launch 'C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe'
2016-06-02 10:37:48> Program: About to launch: 'C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe': 
2016-06-02 10:38:49> Program: Starting Squirrel Updater: --download http://updateserver.com/MyApp/latest
2016-06-02 10:38:49> Program: Fetching update information, downloading from http://updateserver.com/MyApp/latest
2016-06-02 10:38:49> CheckForUpdateImpl: Using existing staging user ID: fea438ee-8eab-5e22-943d-89a05319c816
2016-06-02 10:38:49> CheckForUpdateImpl: Downloading RELEASES file from http://updateserver.com/MyApp/latest
2016-06-02 10:38:49> FileDownloader: Downloading url: http://updateserver.com/MyApp/latest/RELEASES?id=MyApp&localVersion=0.4.7&arch=amd64
2016-06-02 10:38:49> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-06-02 10:38:49> FileDownloader: Downloading file: http://updateserver.com/MyApp/latest/MyApp-0.4.7-ia32-full.nupkg
2016-06-02 10:39:00> UpdateInfo: Couldn't get release notes for:MyApp-0.4.7-ia32-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\IEUser\AppData\Local\MyApp\packages\MyApp-0.4.7-ia32-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2016-06-02 10:39:00> Program: Starting Squirrel Updater: --update http://updateserver.com/MyApp/latest
2016-06-02 10:39:00> Program: Starting update, downloading from http://updateserver.com/MyApp/latest
2016-06-02 10:39:00> Program: About to update to: C:\Users\IEUser\AppData\Local\MyApp
2016-06-02 10:39:00> CheckForUpdateImpl: Using existing staging user ID: fea438ee-8eab-5e22-943d-89a05319c816
2016-06-02 10:39:00> CheckForUpdateImpl: Downloading RELEASES file from http://updateserver.com/MyApp/latest
2016-06-02 10:39:00> FileDownloader: Downloading url: http://updateserver.com/MyApp/latest/RELEASES?id=MyApp&localVersion=0.4.7&arch=amd64
2016-06-02 10:39:01> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-06-02 10:39:01> FileDownloader: Downloading file: http://updateserver.com/MyApp/latest/MyApp-0.4.7-ia32-full.nupkg
2016-06-02 10:39:13> ApplyReleasesImpl: Writing files to app directory: C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\MyApp.exe to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\MyApp.exe
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\content_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\content_resources_200_percent.pak
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\content_shell.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\content_shell.pak
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\d3dcompiler_47.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\d3dcompiler_47.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\ffmpeg.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\ffmpeg.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\icudtl.dat to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\icudtl.dat
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\libGLESv2.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\libGLESv2.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\libEGL.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\libEGL.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\LICENSE to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\LICENSE
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\msvcp120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\msvcp120.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\LICENSES.chromium.html to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\LICENSES.chromium.html
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\msvcr120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\msvcr120.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\natives_blob.bin to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\natives_blob.bin
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\snapshot_blob.bin to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\snapshot_blob.bin
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\ui_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\ui_resources_200_percent.pak
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\node.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\node.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\Update.exe to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\Update.exe
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\vccorlib120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\vccorlib120.dll
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\version to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\version
2016-06-02 10:39:15> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\xinput1_3.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\xinput1_3.dll
2016-06-02 10:39:16> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe]
2016-06-02 10:39:17> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: Slack.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2016-06-02 10:39:17> ApplyReleasesImpl: Fixing up tray icons
2016-06-02 10:39:17> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-06-02 10:39:17> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-06-02 10:39:17> ApplyReleasesImpl: cleanDeadVersions: for version 0.4.7
2016-06-02 10:39:17> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.4.7
2016-06-02 10:39:17> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.4.7
```

After I restart the app, the log shows the same behavior again:
```
2016-06-02 10:46:33> Program: Starting Squirrel Updater: --processStart MyApp.exe
2016-06-02 10:46:33> Program: Want to launch 'C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe'
2016-06-02 10:46:33> Program: About to launch: 'C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe': 
2016-06-02 10:47:34> Program: Starting Squirrel Updater: --download http://updateserver.com/MyApp/latest
2016-06-02 10:47:34> Program: Fetching update information, downloading from http://updateserver.com/MyApp/latest
2016-06-02 10:47:34> CheckForUpdateImpl: Using existing staging user ID: fea438ee-8eab-5e22-943d-89a05319c816
2016-06-02 10:47:34> CheckForUpdateImpl: Downloading RELEASES file from http://updateserver.com/MyApp/latest
2016-06-02 10:47:34> FileDownloader: Downloading url: http://updateserver.com/MyApp/latest/RELEASES?id=MyApp&localVersion=0.4.7&arch=amd64
2016-06-02 10:47:35> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-06-02 10:47:35> FileDownloader: Downloading file: http://updateserver.com/MyApp/latest/MyApp-0.4.7-ia32-full.nupkg
2016-06-02 10:47:47> UpdateInfo: Couldn't get release notes for:MyApp-0.4.7-ia32-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\IEUser\AppData\Local\MyApp\packages\MyApp-0.4.7-ia32-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2016-06-02 10:47:47> Program: Starting Squirrel Updater: --update http://updateserver.com/MyApp/latest
2016-06-02 10:47:47> Program: Starting update, downloading from http://updateserver.com/MyApp/latest
2016-06-02 10:47:47> Program: About to update to: C:\Users\IEUser\AppData\Local\MyApp
2016-06-02 10:47:47> CheckForUpdateImpl: Using existing staging user ID: fea438ee-8eab-5e22-943d-89a05319c816
2016-06-02 10:47:47> CheckForUpdateImpl: Downloading RELEASES file from http://updateserver.com/MyApp/latest
2016-06-02 10:47:47> FileDownloader: Downloading url: http://updateserver.com/MyApp/latest/RELEASES?id=MyApp&localVersion=0.4.7&arch=amd64
2016-06-02 10:47:47> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-06-02 10:47:47> FileDownloader: Downloading file: http://updateserver.com/MyApp/latest/MyApp-0.4.7-ia32-full.nupkg
2016-06-02 10:48:02> ApplyReleasesImpl: Writing files to app directory: C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\content_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\content_resources_200_percent.pak
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\MyApp.exe to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\MyApp.exe
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\content_shell.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\content_shell.pak
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\d3dcompiler_47.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\d3dcompiler_47.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\ffmpeg.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\ffmpeg.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\icudtl.dat to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\icudtl.dat
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\libEGL.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\libEGL.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\libGLESv2.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\libGLESv2.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\LICENSES.chromium.html to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\LICENSES.chromium.html
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\msvcp120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\msvcp120.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\LICENSE to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\LICENSE
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\msvcr120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\msvcr120.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\natives_blob.bin to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\natives_blob.bin
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\snapshot_blob.bin to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\snapshot_blob.bin
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\node.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\node.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\ui_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\ui_resources_200_percent.pak
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\Update.exe to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\Update.exe
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\vccorlib120.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\vccorlib120.dll
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\version to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\version
2016-06-02 10:48:04> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\lib\net45\xinput1_3.dll to C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7-ia32\xinput1_3.dll
2016-06-02 10:48:05> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IEUser\AppData\Local\MyApp\app-0.4.7\MyApp.exe]
2016-06-02 10:48:06> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: Slack.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2016-06-02 10:48:06> ApplyReleasesImpl: Fixing up tray icons
2016-06-02 10:48:06> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-06-02 10:48:06> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-06-02 10:48:06> ApplyReleasesImpl: cleanDeadVersions: for version 0.4.7
2016-06-02 10:48:06> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.4.7
2016-06-02 10:48:06> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.4.7
```

**Comment by ccnokes** [comment]
Looks like the issue is really this: https://github.com/electron-userland/electron-builder/issues/359#issuecomment-218746118
