### ISSUE TITLE
Failed to compile WiX template

### ISSUE THREAD

**Issue by michaelknoch** [electron/windows-installer#124]
I tried to generate an installer for my project, but i receive an error because of an legal identifier error thrown by wix. I also tried to rename my project, rename exe, rename setup exe etc. but i cant'find out where this name with the illegal "-" is set. Can someone help me please? 

thank you

These are my two gulp tasks generating the app and installer for windows:

``` javascript
gulp.task('electron.windows.build', ['production'], function() {

  shell.task([
      'rm -rf mia-win32-x64',
      './node_modules/.bin/electron-packager production mia --platform=win32 --arch=x64 --icon icon.icns --overwrite'], {ignoreErrors: true})

});

gulp.task('electron.windows.setup', ['electron.windows.build'], function() {
    var electronInstaller = require('electron-winstaller');
    electronInstaller.createWindowsInstaller({
      appDirectory: 'mia-win32-x64',
      outputDirectory: 'out/win',
      authors: 'Michael Knoch',
      exe: 'mia.exe',
      title: '123mia',
      setupExe: '123mia_setup.exe',
      description: 'Mia Frontend installer',
      arch: 'x64'
    });

});
```

error thrown:

```
Unhandled rejection Error: Failed with exit code: 4294967295
Output:

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Ex                                                                       ception: Failed to compile WiX template, command invoked was: 'candle.exe -nolog                                                                       o -ext WixNetFxExtension -out "D:\repos\mia\out\win\Setup.wixobj" "D:\repos\mia\                                                                       out\win\Setup.wxs"'

Output was:
Setup.wxs
D:\repos\mia\out\win\Setup.wxs(20) : error CNDL0014 : The Component/@Id attribut                                                                       e's value, 'mia-electron.exe', is not a legal identifier.  Identifiers may conta                                                                       in ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every id                                                                       entifier must begin with either a letter or an underscore.
D:\repos\mia\out\win\Setup.wxs(21) : error CNDL0014 : The File/@Id attribute's v                                                                       alue, 'mia-electron.exe', is not a legal identifier.  Identifiers may contain AS                                                                       CII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identif                                                                       ier must begin with either a letter or an underscore.
D:\repos\mia\out\win\Setup.wxs(34) : error CNDL0014 : The ComponentRef/@Id attri                                                                       bute's value, 'mia-electron.exe', is not a legal identifier.  Identifiers may co                                                                       ntain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every                                                                        identifier must begin with either a letter or an underscore.
   bei Squirrel.Update.Program.<createMsiPackage>d__20.MoveNext()
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancele                                                                       dExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationT                                                                       oken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei Squirrel.Update.Program.Releasify(String package, String targetDir, Strin                                                                       g packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,                                                                        String baseUrl, String setupIcon, Boolean generateMsi)
   bei Squirrel.Update.Program.executeCommandLine(String[] args)
   bei Squirrel.Update.Program.main(String[] args)
   bei Squirrel.Update.Program.Main(String[] args)
---> (Interne Ausnahme #0) System.Exception: Failed to compile WiX template, com                                                                       mand invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "D:\repos\mia\                                                                       out\win\Setup.wixobj" "D:\repos\mia\out\win\Setup.wxs"'

Output was:
Setup.wxs
D:\repos\mia\out\win\Setup.wxs(20) : error CNDL0014 : The Component/@Id attribut                                                                       e's value, 'mia-electron.exe', is not a legal identifier.  Identifiers may conta                                                                       in ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every id                                                                       entifier must begin with either a letter or an underscore.
D:\repos\mia\out\win\Setup.wxs(21) : error CNDL0014 : The File/@Id attribute's v                                                                       alue, 'mia-electron.exe', is not a legal identifier.  Identifiers may contain AS                                                                       CII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identif                                                                       ier must begin with either a letter or an underscore.
D:\repos\mia\out\win\Setup.wxs(34) : error CNDL0014 : The ComponentRef/@Id attri                                                                       bute's value, 'mia-electron.exe', is not a legal identifier.  Identifiers may co                                                                       ntain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every                                                                        identifier must begin with either a letter or an underscore.
   bei Squirrel.Update.Program.<createMsiPackage>d__20.MoveNext()<---


    at ChildProcess.<anonymous> (D:\repos\mia\node_modules\electron-winstaller\l                                                                       ib\spawn-promise.js:62:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

**Comment by domachine** [comment]
Hey. I just had the same problem. The name of the exe is specified by your package's name set in the the `package.json`. I set this to a value without a dash and it worked.

**Comment by sdkcarlos** [comment]
Indeed, changing the name property of the `package.json` file of the build folder (`build-appx64\resources\app\package.json`) did the trick for me too.

**Comment by knuton** [comment]
For anyone running into the same issue:

You shouldn't have to change the name of your project just to address this. A better solution is to explicitly set `name` in [the configuration passed to `createWindowsInstaller`](https://github.com/electron/windows-installer#usage), which overrides the value from `package.json`.

**Comment by isekaimaou1109** [comment]
@knuton I had the same issue even though i have config like you said, but it's not worked as expected :(
