### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by NugzarGaguliya** [electron/windows-installer#140]
Can any body help with this error?

```
Unhandled rejection Error: Failed with exit code: 4294967295
Output:
System.AggregateException: ��������� ���� ��� ��������� ������. ---> System.Exception: Failed to modify resources, command invoked was: 'C:\Users\������\WebstormProjects\electron\node_modules\electron-winstaller\vendor\rcedit.exe "C:\Users\������\WebstormProjects\electron\winstaller\Setup.exe" --set-version-string "CompanyName" "IT Flakes" --set-version-string "LegalCopyright" "Copyright � 2016 IT Flakes" --set-version-string "FileDescription" "Electron based web app for Denti32" --set-version-string "ProductName" "Electron based web app for Denti32" --set-file-version 3.0.3 --set-product-version 3.0.3 --set-icon "C:\Users\������\WebstormProjects\electron\images\1024x1024.ico"'

Output was:
Fatal error: Unable to load file
   � Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__a2.MoveNext()
   --- ����� ����������� ����������� ����� ���������� ---
   � System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   � System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   � Squirrel.Update.Program.<>c__DisplayClass78.<Releasify>b__72()
   � Squirrel.Utility.<>c__DisplayClassc.<Retry>b__b()
   � Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   � Squirrel.Utility.Retry(Action block, Int32 retries)
   � Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
   � Squirrel.Update.Program.Main(String[] args)
---> (���������� ���������� #0) System.Exception: Failed to modify resources, command invoked was: 'C:\Users\������\WebstormProjects\electron\node_modules\electron-winstaller\vendor\rcedit.exe "C:\Users\������\WebstormProjects\electron\winstaller\Setup.exe" --set-version-string "CompanyName" "IT Flakes" --set-version-string "LegalCopyright" "Copyright � 2016 IT Flakes" --set-version-string "FileDescription" "Electron based web app for Denti32" --set-version-string "ProductName" "Electron based web app for Denti32" --set-file-version 3.0.3 --set-product-version 3.0.3 --set-icon "C:\Users\������\WebstormProjects\electron\images\1024x1024.ico"'

Output was:
Fatal error: Unable to load file
   � Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__a2.MoveNext()<---


    at ChildProcess.proc.on.code (C:\Users\Нугзар\WebstormProjects\electron\node_modules\electron-winstaller\lib\spawn-promise.js:62:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Process finished with exit code 0
```

**Comment by NugzarGaguliya** [comment]
problem with folder name
