### ISSUE TITLE
error while building from nuget

### ISSUE THREAD

**Issue by shrynx** [electron/windows-installer#152]
This is the error stack, I replaced my app's name with ```<AppName>```
```js
Unhandled rejection Error: Failed with exit code: 1
Output:
Attempting to build package from '<AppName>.nuspec'.
File not found: '<AppName>'.

    at ChildProcess.<anonymous> (C:\Users\shriyans.bhatnagar\projects\node_modules\electron-winstaller\lib\spawn-promise.js:62:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
```

**Comment by lenin-anzen** [comment]
I am getting the same error, the name of the app is:

- foo-bar-baz

But the name of the .exe file that the windows-installer is looking is **foo-bar**:

```
No dice: Failed with exit code: 1
Output:
Attempting to build package from 'foo-bar-baz.nuspec'.
File not found: 'foo-bar.exe'.
```
