### ISSUE TITLE
32-bit build regression: System.AggregateException The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by Thomas101** [electron/windows-installer#184]
**Operating System** Windows 10. **32-bit only**

**Version:** 2.6.0, 2.6.1, 2.6.2, 2.6.3. **Does not affect 2.5.2 & earlier**

When using `electronInstaller.createWindowsInstaller()` I've started seeing the error below. This only affects 32 bit versions of windows. After downgrading the to 2.5.2 it starts working again.

```
Error: Failed with exit code: 4294967295
Output:
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugge rNotification(Task task)
at Squirrel.Utility.<ExtractZipToDirectory>d__22.MoveNext() --- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,
CancellationToken cancellationToken)
at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String
packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
at Squirrel.Update.Program.executeCommandLine(String[] args) at Squirrel.Update.Program.main(String[] args)
at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugge rNotification(Task task)
at Squirrel.Utility.<ExtractZipToDirectory>d__22.MoveNext()<---
at ChildProcess.proc.on.code (C: \Users\app\node_modules\electron- winstaller\lib\spawn-promise.js:62h16)
at emitTwo (events.js:106h13)
at ChildProcess.emit (events.js:194h7)
at maybeClose (internal/child_process.js:899h16)
at Socket.<anonymous> (internal/child_process.js:342h11) at emitOne (events.js:101h20)
at Socket.emit (events.js:191h7)
at Pipe._handle.close [as _onclose] (net.js:510h12)
```

**Comment by ianli-sc** [comment]
+1

**Comment by dnovaes** [comment]
+1

**Comment by abdurrahmanekr** [comment]
I have that same problem. 
OS: Windows 7 32bit only
Windows-installer version: 2.6.3

**Comment by Bertik750** [comment]
+1

**Comment by Manishbatra4** [comment]
any solution?

**Comment by abdurrahmanekr** [comment]
I think I solved the problem by adding `--arch=32` to electron-packager. 
```
electron-packager . App --platform=win32 --arch=ia32
```

**Comment by claudiafinn** [comment]
+1, using --arch=ia32 and still seeing this issue

**Comment by cfinn0510** [comment]
+1, using --arch=ia32 and still seeing this issue
Win10 32 bits

**Comment by cfinn0510** [comment]
We were actually still installing the 64 bit version. Using electron-packager and --arch=ia32 works for us on a 32 bit Windows 10 VM.

**Comment by Thomas101** [comment]
@abdurrahmanekr @cfinn0510 the issue you're seeing is with [electron-packager](https://github.com/electron-userland/electron-packager) not this repository [windows-installer](https://github.com/electron/windows-installer).

The issue still occurs in 2.6.4

**Comment by romaincointepas** [comment]
Could it be related to this: https://github.com/Squirrel/Squirrel.Windows/issues/1148#issuecomment-328932091?

cc @paulcbetts

**Comment by adabru** [comment]
From same issue (https://github.com/Squirrel/Squirrel.Windows/issues/1148#issuecomment-354074569):

lukywong:
> paulcbetts is it possible to support 32-bit version of windows? because i really want it support

anaisbetts:
> lukywong No, sorry! While the installer you build will support 32-bit computers (i.e. your users can have 32-bit OS), your computer must be 64-bit.

Guessing this issue can be closed.
