### ISSUE TITLE
error on packaging

### ISSUE THREAD

**Issue by EVOKE-LEKTRIQUE** [electron/windows-installer#200]
windows 7 32 bit
electron 1.7.5

when i want to pack my app i get this error:
node createinstaller.js
creating windows installer

Failed with exit code: 4294967295
Output:
System.AggregateException: One or more errors occurred. ---> System.ComponentMode
l.Win32Exception: The specified executable is not a valid application for this OS
 platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInf
o)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNoti
fication(Task task)
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledE
xceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTok
en cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pack
agesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, St
ring baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boo
lean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The
specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInf
o)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNoti
fication(Task task)
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---

what it means ??

**Comment by ianli-sc** [comment]
+1

**Comment by jsonphper** [comment]
+1

**Comment by anaisbetts** [comment]
You cannot use 32-bit Windows to package Squirrel apps, sorry
