### ISSUE TITLE
Setup.exe installation failed.

### ISSUE THREAD

**Issue by vibinmj** [electron/windows-installer#218]
In electron app,its been packaged by electron-packager and using electron-winstaller ,electron-squirrel-startup and also electron-rebuild in my package.json .i have been able to create windows installer (.exe) ,but whenever i tries to install it it says installation is failed ,but when i looked into appdata i can found a folder named after my app and also contents in it.

![installationerror](https://user-images.githubusercontent.com/34235481/34068849-54f446d6-e269-11e7-83c2-3c51b2731f6c.PNG)

This is what the log says.,

2017-12-13 12:51:49> Program: Starting Squirrel Updater: --install .
2017-12-13 12:51:50> Program: Starting install, writing to C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 12:51:50> Program: About to install to: C:\Users\TEST-VM-PC\AppData\Local\angular-electron
2017-12-13 12:51:50> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages.betaId'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-12-13 12:51:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-12-13 12:51:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 12:51:50> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-12-13 12:51:50> ApplyReleasesImpl: Writing files to app directory: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0
2017-12-13 12:51:51> LogHost: Rigging execution stub for angular-electron_ExecutionStub.exe to C:\Users\TEST-VM-PC\AppData\Local\angular-electron\angular-electron.exe
2017-12-13 12:51:53> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe]
2017-12-13 12:52:09> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe: System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Squirrel.Utility.<>c__DisplayClass11_0.b__0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<b__0>d.MoveNext()
2017-12-13 12:52:09> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-12-13 12:52:09> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-12-13 12:52:09> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-12-13 12:52:09> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2017-12-13 12:52:09> ApplyReleasesImpl: Fixing up tray icons
2017-12-13 12:52:09> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 12:52:09> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 12:52:09> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2017-12-13 12:52:09> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
2017-12-13 12:52:10> IEnableLogger: Failed to create uninstaller registry entry: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at NuGet.ZipPackage..ctor(String filePath)
at Squirrel.UpdateManager.InstallHelperImpl.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__431.MoveNext() 2017-12-13 12:52:10> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) at System.Uri..ctor(String uriString) at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl() at NuGet.LocalPackage.ReadManifest(Stream manifestStream) at NuGet.ZipPackage.EnsureManifest() at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching) at NuGet.ZipPackage..ctor(String filePath) at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Utility.<LogIfThrows>d__431.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at NuGet.ZipPackage..ctor(String filePath)
at Squirrel.UpdateManager.InstallHelperImpl.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()<---

2017-12-13 13:36:21> Program: Starting Squirrel Updater: --install .
2017-12-13 13:36:21> Program: Starting install, writing to C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 13:36:21> Program: About to install to: C:\Users\TEST-VM-PC\AppData\Local\angular-electron
2017-12-13 13:36:21> Program: Install path C:\Users\TEST-VM-PC\AppData\Local\angular-electron already exists, burning it to the ground
2017-12-13 13:36:22> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages.betaId'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-12-13 13:36:22> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-12-13 13:36:22> CheckForUpdateImpl: Reading RELEASES file from C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 13:36:22> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-12-13 13:36:22> ApplyReleasesImpl: Writing files to app directory: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0
2017-12-13 13:36:23> LogHost: Rigging execution stub for angular-electron_ExecutionStub.exe to C:\Users\TEST-VM-PC\AppData\Local\angular-electron\angular-electron.exe
2017-12-13 13:36:26> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe]
2017-12-13 13:36:42> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe: System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Squirrel.Utility.<>c__DisplayClass11_0.b__0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<b__0>d.MoveNext()
2017-12-13 13:36:42> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-12-13 13:36:42> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-12-13 13:36:42> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-12-13 13:36:42> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2017-12-13 13:36:42> ApplyReleasesImpl: Fixing up tray icons
2017-12-13 13:36:42> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 13:36:42> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 13:36:42> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2017-12-13 13:36:42> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
2017-12-13 13:36:42> IEnableLogger: Failed to create uninstaller registry entry: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at NuGet.ZipPackage..ctor(String filePath)
at Squirrel.UpdateManager.InstallHelperImpl.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__431.MoveNext() 2017-12-13 13:36:42> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) at System.Uri..ctor(String uriString) at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl() at NuGet.LocalPackage.ReadManifest(Stream manifestStream) at NuGet.ZipPackage.EnsureManifest() at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching) at NuGet.ZipPackage..ctor(String filePath) at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Utility.<LogIfThrows>d__431.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at NuGet.ZipPackage..ctor(String filePath)
at Squirrel.UpdateManager.InstallHelperImpl.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()<---

2017-12-13 16:14:24> Program: Starting Squirrel Updater: --install .
2017-12-13 16:14:24> Program: Starting install, writing to C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 16:14:24> Program: About to install to: C:\Users\TEST-VM-PC\AppData\Local\angular-electron
2017-12-13 16:14:24> Program: Install path C:\Users\TEST-VM-PC\AppData\Local\angular-electron already exists, burning it to the ground
2017-12-13 16:14:24> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages.betaId'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-12-13 16:14:24> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\TEST-VM-PC\AppData\Local\angular-electron\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-12-13 16:14:24> CheckForUpdateImpl: Reading RELEASES file from C:\Users\TEST-VM-PC\AppData\Local\SquirrelTemp
2017-12-13 16:14:24> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-12-13 16:14:24> ApplyReleasesImpl: Writing files to app directory: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0
2017-12-13 16:14:26> LogHost: Rigging execution stub for angular-electron_ExecutionStub.exe to C:\Users\TEST-VM-PC\AppData\Local\angular-electron\angular-electron.exe
2017-12-13 16:14:28> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe]
2017-12-13 16:14:44> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\TEST-VM-PC\AppData\Local\angular-electron\app-1.0.0\angular-electron.exe: System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Squirrel.Utility.<>c__DisplayClass11_0.b__0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<b__0>d.MoveNext()
2017-12-13 16:14:44> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-12-13 16:14:44> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-12-13 16:14:44> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-12-13 16:14:44> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2017-12-13 16:14:44> ApplyReleasesImpl: Fixing up tray icons
2017-12-13 16:14:44> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 16:14:44> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__13_0(RegistryView view)
2017-12-13 16:14:44> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2017-12-13 16:14:44> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
2017-12-13 16:14:44> IEnableLogger: Failed to create uninstaller registry entry: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePat

Ant workaround or solution is appreciated.
Thanking you,

**Comment by luozhihua** [comment]
Same problem!

**Comment by mitchwilliamson** [comment]
Was fighting with this issue for a while, turns out the Squirrel version included in the current version of this package is causing the issue. There is a pull request that fixes it that hasn't been merged yet. https://github.com/electron/windows-installer/pull/223

I applied the pull request to my local package, built the installer and it installed without the error.

**Comment by mitchwilliamson** [comment]
Was also fighting with this issue, updating to v2.6.4 of this package fixed it.
