### ISSUE TITLE
IDR_UPDATE_ZIP not replaced

### ISSUE THREAD

**Issue by dominicrico** [electron/windows-installer#237]
Hey,

I`m on Windows 10 trying to build my installer and can't get it to work.
My `Foo Setup.exe` is always ~500kb small and I`m getting and error showing me that this is a dummy updater.exe.

There is **no error** in the logs (Squirrel and this package)

I`ve used several versions of NodeJS and all kind of versions of this package, without luck.

Building ia32 or x64 doesn`t make a difference. I`m not building an MSI installer.

Any help would be awesome!

**Comment by baconbrad** [comment]
Having the same issue. I noticed it gets flagged as ransomware by Malware-bytes now.

**Comment by baconbrad** [comment]
Deleted the dependency in my node_modules and reinstalled it. Works fine and is not longer flagged by my antivirus software. My guess is `IDR_UPDATE_ZIP not replaced` is shown when the Update.exe isn't properly bundled. Double check and make sure your AV isn't blocking the operation that copies it over.

**Comment by dominicrico** [comment]
@baconbrad Thanks for the hint! I will check that asap.

**Comment by kumar67** [comment]
I resolved this by adding the folder that contains squirrel.exe to the environmental path variable.

**Comment by yalzeee** [comment]
@dominicrico 
@baconbrad  @kumar67 @paulcbetts @fserb 
Facing the same issue with this error on log
2019-03-02 01:01:47> Program: Starting Squirrel Updater: --install .
2019-03-02 01:01:47> Program: Starting install, writing to C:\Users\Oyale Peter\AppData\Local\SquirrelTemp
2019-03-02 01:01:47> Program: About to install to: C:\Users\Oyale Peter\AppData\Local\thebusinessapp
2019-03-02 01:01:48> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Oyale Peter\AppData\Local\thebusinessapp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-03-02 01:01:48> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Oyale Peter\AppData\Local\thebusinessapp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()

It was working before now but started giving off these errors

**Comment by puruzio** [comment]
@dominicrico  I'm having the same issue. Were you able to fix it?

**Comment by yalzeee** [comment]
Yeah it was an anti virus issue. Disabled my antivirus, then built

**Comment by puruzio** [comment]
It's still creating a small (200k) dummy Setup.exe fIle even though Windows Defender is turned off, and there is no other anti-virus program installed. This issue didn't start up until 2 days ago out of nowhere. I never had any issue like this before, and the Setup file size was pretty consistently 200mb + in the past.

**Comment by yalzeee** [comment]
If the issue keeps persisting I'd recommend you try out electron-builder

**Comment by evandrosimenes** [comment]
in my case, by deleting the unpackage output folder and rebuilding all solved the issue.
I supposed that i've tested that with another plugin (electron-installer-windows) and have builded all with that and then back to electron-winstaller trying to generate without building again (dont forget to delete all output folders)... it seems that some unpackage output build folder owner was the issue...
