### ISSUE TITLE
Getting error when packaging nativefier app.

### ISSUE THREAD

**Issue by jraspiprojects** [electron/windows-installer#261]
I packaged a application for Google Hangouts and i get this error
C:\Users\jrasp\nativefier\hangout>node install.js
No dice: Failed with exit code: 4294967295
Output:
System.Exception: Your package version is currently 1.0.0.0, which is *not* SemVer-compatible, change this to be a SemVer version number
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

**Comment by alexanderturinske** [comment]
Relates to #264

**Comment by BigSteel** [comment]
same here, is there a solution?
