### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by cristiammercado** [electron/windows-installer#294]
Hi,

I recently updated `electron-winstaller` to the latest published version `3.0.0` but apparently there is an error that does not allow creating the installer under Windows environment.

I saw the error had been reported before here #8 , but I'm not sure if it's the same error.

OS: Windows 10 x64
Node: v10.15.1
npm: 6.8.0

Error trace:

```node
[11:48:22] ReferenceError: regeneratorRuntime is not defined
    at Object._createWindowsInstaller (D:\blablabla\node_modules\electron-winstaller\lib\index.js:47:3)
    at Object.createWindowsInstaller (D:\blablabla\node_modules\electron-winstaller\lib\index.js:41:34)
    at execWin32 (D:blablabla\tasks\executable.js:51:38)
    at taskWrapper (D:\blablabla\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (D:\blablabla\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

index.js library file fragment:
```
44: function _createWindowsInstaller() {
45:   _createWindowsInstaller = _asyncToGenerator(
46:   /*#__PURE__*/
47:   regeneratorRuntime.mark(function _callee(options) {
48:     var useMono, monoExe, wineExe, appDirectory, outputDirectory, loadingGif, vendorPath, vendorUpdate, appUpdate, _cmd, _args, defaultLoadingGif, certificateFile, certificatePassword, remoteReleases, signWithParams, remoteToken, metadata, appResources, asarFile, appMetadata, templateData, nuspecContent, nugetOutput, targetNuspecPath, cmd, args, nupkgPath, setupPath, unfixedSetupPath, msiPath, unfixedMsiPath;
49: 
50:     return regeneratorRuntime.wrap(function _callee$(_context) {
51:       while (1) {
52:         switch (_context.prev = _context.next) {
53:           case 0:
54:             useMono = false;
55:             monoExe = 'mono';
56:             wineExe = 'wine';
```

Thanks in advance.

**Comment by MarshallOfSound** [comment]
Hey @cristiammercado sorry about that, should be fixed in `3.0.1` now 👍
