### ISSUE TITLE
await electronInstaller.createWindowsInstaller

### ISSUE THREAD

**Issue by Klinsman21** [electron/windows-installer#321]
SyntaxError: await is only valid in async function
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by akkaradej** [comment]
I also have this issue. I use Promise.then instead of await to fix error.

**Comment by jingweihaha** [comment]
> I also have this issue. I use Promise.then instead of await to fix error.

I solved it using Promise.then as well, the code below you may refer to:

```
const electronInstaller = require('electron-winstaller');
// try {
electronInstaller.createWindowsInstaller({
    appDirectory: '',
    outputDirectory: './dist',
    authors: 'My App Inc.',
    exe: 'myapp.exe'
}).then(() =>{console.log('It worked!');}).catch(function(error){
    console.log(error);
});
```

**Comment by malept** [comment]
The docs were clarified in https://github.com/electron/windows-installer/commit/e193923420894f11ec77652c41ed1c435b26cb2d#diff-04c6e90faac2675aa89e2176d2eec7d8
