### ISSUE TITLE
Can't find custom attr constructor image with nuget.exe

### ISSUE THREAD

**Issue by AhmadIbrahiim** [electron/windows-installer#325]
I'm using `electron-forge` which is based on windows-installer and when I try to `make` an `win32` image it throws the error below from `windows-installer`:
```
=================================================================================

ENV Summary:

  TIME: Sat Jan 18 2020 13:01:20 GMT+0200 (Eastern European Standard Time)
  TITLE: ember
  ARGV:
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin/node
  - /home/ahmed/Desktop/MaxmioTech/linkedinscraper/node_modules/.bin/ember
  - electron:make
  - --platform
  - win32
  EXEC_PATH: /home/ahmed/.nvm/versions/node/v10.17.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1579345033732-0.999521156327345
  - /home/ahmed/Desktop/MaxmioTech/linkedinscraper/node_modules/.bin
  - /home/ahmed/.config/yarn/link/node_modules/.bin
  - /home/ahmed/.nvm/versions/node/v10.17.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/ahmed/.nvm/versions/node/v10.17.0/lib/node_modules/npm/bin/node-gyp-bin
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin/node_modules/npm/bin/node-gyp-bin
  - /home/ahmed/.yarn/bin
  - /home/ahmed/.config/yarn/global/node_modules/.bin
  - /home/ahmed/.yarn/bin
  - /home/ahmed/.config/yarn/global/node_modules/.bin
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 856813568
  TOTALMEM: 8234668032
  UPTIME: 420
  LOADAVG: 2.35546875,1.86962890625,0.97705078125
  CPUS:
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2500
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2670
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2524
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2560
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 5
  - nghttp2: 1.39.2
  - node: 10.17.0
  - openssl: 1.1.1d
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: An error occured while making for target: squirrel
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: An error occured while making for target: squirrel
  - name: [undefined]
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Failed with exit code: 255
Output:

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
Can't find custom attr constructor image: /home/ahmed/Desktop/MaxmioTech/linkedinscraper/node_modules/electron-forge/node_modules/electron-winstaller/vendor/nuget.exe mtoken: 0x0a000a76 due to Could not load file or assembly or one of its dependencies. assembly:System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>

Error: Failed with exit code: 255
Output:

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
Can't find custom attr constructor image: /home/ahmed/Desktop/MaxmioTech/linkedinscraper/node_modules/electron-forge/node_modules/electron-winstaller/vendor/nuget.exe mtoken: 0x0a000a76 due to Could not load file or assembly or one of its dependencies. assembly:System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>

    at ChildProcess.proc.on.code (/home/ahmed/Desktop/MaxmioTech/linkedinscraper/node_modules/electron-forge/node_modules/electron-winstaller/lib/spawn-promise.js:62:16)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

=================================================================================

```

**Comment by elsantoalcielo** [comment]
You have to install mono-devel, it won't work with just mono-runtime.
