### ISSUE TITLE
Failed with exit code: 4294967295 , unable to create Setup.wxs or Setup.msi - any help please?

### ISSUE THREAD

**Issue by onelsonic** [electron/windows-installer#329]
Hi there, does anyone has encounter this issue ?? 

I removed any special characters in my APP name.
my building script is below :

```
var electronInstaller = require('electron-winstaller');

// In this case, we can use relative paths
var settings = {
	name: "myAPP",
	version: "1.0.0",
	description: "my description",
    // Specify the folder where the built app is located
    appDirectory: './myAPP',
    // Specify the existing folder where 
    outputDirectory: './myAPPinstallers',
    // The name of the Author of the app (the name of your company)
    authors: 'myAPP',
	exe: 'myAPP.exe',
	setupMsi: './myAPP.msi',
	setupIcon: './icon.ico'
};

resultPromise = electronInstaller.createWindowsInstaller(settings);
 
resultPromise.then(() => {
    console.log("The installers of your application were succesfully created !");
}, (e) => {
    console.log(`Well, sometimes you are not so lucky: ${e.message}`)
}); 
```

my **package.json** file : 

```
{
	"main": "lib/main.js",
	"dependencies": {"electron-context-menu": "^0.10.0",
	"electron-dl": "^1.10.0",
	"electron-squirrel-startup": "^1.0.0",
	"electron-window-state": "^4.1.1",
	"loglevel": "^1.5.1",
	"source-map-support": "^0.5.0",
	"wurl": "^2.5.2"},
	"devDependencies": {},
	"scripts": {"test": "echo \"Error:  no test specified\" && exit 1"},
	"keywords": ["desktop",
	"electron"]
}
```

but I keep getting the following errors:

```
C:\Users\onelsonic\electron_winstaller>node build_installer.js
Well, sometimes you are not so lucky: Failed with exit code: 4294967295
Output:

System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wixobj" "C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs"'

Output was:
Setup.wxs
C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs(2) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.myAPP.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs(2) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
   at Squirrel.Update.Program.<createMsiPackage>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wixobj" "C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs"'

Output was:
Setup.wxs
C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs(2) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.myAPP.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
C:\Users\onelsonic\electron_winstaller\myAPPinstallers\Setup.wxs(2) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
   at Squirrel.Update.Program.<createMsiPackage>d__21.MoveNext()<---


```

**Comment by onelsonic** [comment]
seems like a broader problem with eletron and Squirrel
https://github.com/electron/electron/issues/22452
