### ISSUE TITLE
Squirell reports that install failed if custom gif is provided

### ISSUE THREAD

**Issue by adi97ida** [electron/windows-installer#360]
Hello, as the title suggests I am encountering an error popup each time I try to install my packaged app.
This error only happens when I add a custom gif to the installer.

The error popup:
![image](https://user-images.githubusercontent.com/5168792/94262461-d2024300-ff33-11ea-85aa-78422efb16f0.png)

The SquirellSetup log:

> 2020-09-25 13:33:18> Program: Starting Squirrel Updater: --install .
> 2020-09-25 13:33:18> Program: Starting install, writing to C:\Users\USER\AppData\Local\SquirrelTemp
> 2020-09-25 13:33:18> Program: About to install to: C:\Users\USER\AppData\Local\APPNAME
> 2020-09-25 13:33:18> Program: Install path C:\Users\USER\AppData\Local\APPNAME already exists, burning it to the ground
> 2020-09-25 13:33:19> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USER\AppData\Local\APPNAME\packages\.betaId'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
>    at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
> 2020-09-25 13:33:19> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USER\AppData\Local\APPNAME\packages\RELEASES'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
> 2020-09-25 13:33:19> CheckForUpdateImpl: Reading RELEASES file from C:\Users\USER\AppData\Local\SquirrelTemp
> 2020-09-25 13:33:19> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
> 2020-09-25 13:33:19> ApplyReleasesImpl: Writing files to app directory: C:\Users\USER\AppData\Local\APPNAME\app-0.1.6
> 2020-09-25 13:33:21> LogHost: Rigging execution stub for APPNAME_ExecutionStub.exe to C:\Users\USER\AppData\Local\APPNAME\APPNAME.exe
> 2020-09-25 13:33:22> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\USER\AppData\Local\APPNAME\app-0.1.6\APPNAME.exe]
> 2020-09-25 13:33:23> ApplyReleasesImpl: Starting fixPinnedExecutables
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Chrome.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Brave.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Chrome.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: JetBrains WebStorm 2019.2.3.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Slack.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: VNC® Viewer.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Examining Pin: Wireshark.lnk
> 2020-09-25 13:33:23> ApplyReleasesImpl: Fixing up tray icons
> 2020-09-25 13:33:23> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.6
> 2020-09-25 13:33:23> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.6

I care to mention that besides this error message the app actually installs and the update works perfectly.

**Comment by adi97ida** [comment]
I was calling the checkForUpdate on the Electron's auto-updater too fast. Adding it within a setTimeout inside the app.whenReady event solved this issue
