### ISSUE TITLE
no 7zia32.exe in vendor

### ISSUE THREAD

**Issue by dongfeng520** [electron/windows-installer#386]
no 7z-ia32.exe in vendor  ,only 7z-x64.exe

**Comment by MarkusSvensson** [comment]
I faced the same problem and made this workaround (until it is fixed by this pull request https://github.com/electron/windows-installer/pull/378):

1. Run
> npm install --ignore-scripts
to install 5.0.0 without running the failing script (select-7z-arch.js).

2. Manually download .dll & .exe file from https://github.com/electron/windows-installer/pull/378 to the node_modules/electron-winstaller/vendor folder and rename them to 7z.exe and 7z.dll.

**Comment by funding-invoice-admin** [comment]
Hi i got the same problem here, any solution ?
Got this after upddate to Webpack 5.61

`
[4/19] ⠐ electron-winstaller
warning Error running install script for optional dependency: "C:\\Users\\JonasKabalo\\desktop\\fundinginvoice\\admin-electron\\node_modules\\electron-winstaller: Command failed.
Exit code: 1
Command: node ./script/select-7z-arch.js
Arguments:
Directory: C:\\Users\\JonasKabalo\\desktop\\fundinginvoice\\admin-electron\\node_modules\\electron-winstaller
Output:
Selecting 7-Zip for arch ia32
C:\\Users\\JonasKabalo\\desktop\\fundinginvoice\\admin-electron\\node_modules\\electron-winstaller\\script\\select-7z-arch.js:16
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile 'vendor/7z-ia32.exe' -> 'vendor/7z.exe'
    at Object.copyFileSync (fs.js:1991:3)
    at Object.<anonymous> (C:\\Users\\JonasKabalo\\desktop\\fundinginvoice\\admin-electron\\node_modules\\electron-winstaller\\script\\select-7z-arch.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
`

**Comment by AndrewMuise** [comment]
I resolved this by updating my node version from 16.13.0 -> 16.13.2, seems to have been an issue with node itself and how the os module was working

**Comment by jagthedrummer** [comment]
This is still a problem on Windows with node 16.17.0.

**Comment by jagthedrummer** [comment]
After banging my head against this for a while I finally discovered that I had accidentally installed `x86` node instead of `x64` node. Once I switched to `x64` this problem went away.

**Comment by oopses** [comment]
> This is still a problem on Windows with node 16.17.0.



> After banging my head against this for a while I finally discovered that I had accidentally installed `x86` node instead of `x64` node. Once I switched to `x64` this problem went away.



> After banging my head against this for a while I finally discovered that I had accidentally installed `x86` node instead of `x64` node. Once I switched to `x64` this problem went away.



> This is still a problem on Windows with node 16.17.0.
MR merged the branch into Master, but then the Master branch was deleted and switched to the Main branch

https://github.com/electron/windows-installer/pull/378
