### ISSUE TITLE
System.IO.IOException: The file 'C:\Users\appveyor\AppData\Local\Temp\1\tmp35CE.tmp' already exists

### ISSUE THREAD

**Issue by develar** [electron/windows-installer#44]
electron-builder tests very often failed because of error https://ci.appveyor.com/project/stefanjudis/electron-builder/build/1.0.247#L502

@paulcbetts Do you have any clue why? May be Squirrel.Windows cannot be run in parallel?

```× winPackagerTest » win failed with "Failed with exit code: 4294967295
Output:
Done Adding Additional Store
Successfully signed: C:\Users\appveyor\AppData\Local\SquirrelTemp\tempd\lib\net45\TestApp.exe
Done Adding Additional Store
Successfully signed: C:\Users\appveyor\AppData\Local\SquirrelTemp\tempd\lib\net45\squirrel.exe
Done Adding Additional Store
Successfully signed: C:\Users\appveyor\AppData\Local\SquirrelTemp\tempa\Update.exe
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The file 'C:\Users\appveyor\AppData\Local\Temp\1\tmp35CE.tmp' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at Squirrel.Update.Program.<>c__DisplayClass91.<createSetupEmbeddedZip>b__89()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Update.Program.<createSetupEmbeddedZip>d__93.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The file 'C:\Users\appveyor\AppData\Local\Temp\1\tmp35CE.tmp' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at Squirrel.Update.Program.<>c__DisplayClass91.<createSetupEmbeddedZip>b__89()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Update.Program.<createSetupEmbeddedZip>d__93.MoveNext()<---

```
```

**Comment by paulcbetts** [comment]
No idea, but this error is in System.IO.Compression so there's not much we can do about it

**Comment by MarshallOfSound** [comment]
Hey 👋 

This issue is being closed as it is stale.  This normally means that the issue has been fixed in newer versions or this issue or no longer impacting you.  If this is not the case please feel free to comment with and @ mention me and we can revisit this.
