### ISSUE TITLE
Error executing createWindowsInstaller on Windows 10

### ISSUE THREAD

**Issue by CabuxaMapache** [electron/windows-installer#444]
Platform: Windows 10
electron: 8.2.5
electron-packager: 14.2.1
electron-winstaller: 4.0.0

Config:

```
const outPath = Path.join('./', 'release-builds');
const config ={
    appDirectory: Path.join(outPath, 'myApp-win32-x64/'),
    authors: 'Me',
    noMsi: true,
    outputDirectory: Path.join(outPath, 'windows-installer'),
    exe: 'Myapp.exe',
    setupExe: 'MyappAppInstaller.exe',
    setupIcon: Path.join(rootPath, 'dist', 'assets', 'icons', 'win', 'app.ico')
  };
```

Error calling "createWindowsInstaller":

> (node:18024) UnhandledPromiseRejectionWarning: Error: Failed with exit code: 4294967295
> Output:
> System.AggregateException: Se han producido uno o varios errores. ---> System.ComponentModel.Win32Exception: El sistema no puede encontrar el archivo especificado
>    en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    en System.Diagnostics.Process.Start()
>    en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    en Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
> --- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
>    --- Fin del seguimiento de la pila de la excepci�n interna ---
>    en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    en System.Threading.Tasks.Task.Wait()
>    en Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
>    en Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
>    en Squirrel.Update.Program.executeCommandLine(String[] args)
>    en Squirrel.Update.Program.main(String[] args)
>    en Squirrel.Update.Program.Main(String[] args)
> ---> (N� de excepci�n interna 0) System.ComponentModel.Win32Exception (0x80004005): El sistema no puede encontrar el archivo especificado
>    en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    en System.Diagnostics.Process.Start()
>    en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    en Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
> --- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
>     at ChildProcess.<anonymous> (C:\Aplicaciones\FSFAPPS\recuperaciones-electron\dist\node_modules\electron-winstaller\lib\spawn-promise.js:49:24)
>     at ChildProcess.emit (events.js:314:20)
>     at maybeClose (internal/child_process.js:1022:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> (node:18024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:18024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CabuxaMapache** [comment]
I dont know why, but setting environment var with `set DEBUG=electron-windows-installer:main node dist/installers/windows/createinstaller.js` fixed the problem...

**Comment by CabuxaMapache** [comment]
Nop, open installer fails showing error, reopen

**Comment by CabuxaMapache** [comment]
Ok, my fault, reinstalling from zero after deleting node_modules makes the difference, sorry
