### ISSUE TITLE
Windows installer creation fails under OS X

### ISSUE THREAD

**Issue by hzeroo** [electron/windows-installer#47]
Running windows-installer through electron-builder doesnt work creating the installer for Windows (both 32 and 64) under OS X. OS X installer creation works, is just the windows one:

        Packaging app for platform win32 x64 using electron v0.37.2
        Error: Failed with exit code: 1
        Output:
        Intentando compilar el paquete desde 'xxxxxx.nuspec'. 
        ManifestMetadata is required.
        ManifestMetadata is required.
            at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:59:16)
            at emitTwo (events.js:100:13)
            at ChildProcess.emit (events.js:185:7)
            at maybeClose (internal/child_process.js:821:16)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
        From previous event:
            at processImmediate [as _immediateCallback] (timers.js:383:17)
        From previous event:
            at Object.createWindowsInstaller (/usr/local/lib/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:207:16)
            at WinPackager.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/winPackager.ts:123:50)
            at [object Generator].next (native)
        From previous event:
            at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/awaiter.ts:10:51)
            at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:30:55)
            at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:41:2)
            at Module._compile (module.js:413:34)
            at Object.Module._extensions..js (module.js:422:10)
            at Module.load (module.js:357:32)
            at Function.Module._load (module.js:314:12)
            at Function.Module.runMain (module.js:447:10)
            at startup (node.js:139:18)
            at node.js:999:3

Related to:
https://github.com/electron-userland/electron-builder/issues/258

**Comment by develar** [comment]
New stack trace: https://github.com/electron-userland/electron-builder/issues/258#issuecomment-200574256

**Comment by mistermoe** [comment]
experiencing the same issue. 

```
mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

wine --version
wine-1.8.1
```

**Comment by havenchyk** [comment]
Solved in https://github.com/electron-userland/electron-builder/issues/258#issuecomment-200813602
