### ISSUE TITLE
Release notes exception

### ISSUE THREAD

**Issue by havenchyk** [electron/windows-installer#48]
Hi, I've got this exception

```
2016-03-22 12:35:34> UpdateInfo: Couldn't get release notes for:MuApp-0.0.2-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Uladzimir_Havenchyk\AppData\Local\MuApp\packages\MuApp-0.0.2-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
```

@paulcbetts could you please clarify, what's going on and how to fix it?

**Comment by havenchyk** [comment]
The note from paulcbetts:

> the release notes exception is just a warning
Not a crash
