### ISSUE TITLE
Squirrel.Windows ReleaseNotes error causes autoUpdater to download updates twice

### ISSUE THREAD

**Issue by djpereira** [electron/windows-installer#58]
I am using the auto-updater module, and when an update is detected and downloaded, Squirrel logs an exception (see below) and as a result the file gets downloaded twice.

I may be doing something wrong, but as far as I can see, the NUPKG file is getting downloaded twice as I am monitoring the folders.

This issue has been flagged as a red herring, but I am not a 100% if it is an autoUpdater issue or a Squirrel issue. See https://github.com/Squirrel/Squirrel.Windows/issues/136.

```
016-04-04 17:03:09> Program: Starting Squirrel Updater: --download http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:03:09> Program: Fetching update information, downloading from http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:03:09> CheckForUpdateImpl: Downloading RELEASES file from http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:03:09> FileDownloader: Downloading url: http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha/RELEASES?id=lifesize&localVersion=0.1.9-alpha-ia32&arch=amd64
2016-04-04 17:03:11> FileDownloader: Downloading file: http://lsnuts-dev.us-east-1.elasticbeanstalk.com/download/0.1.10-alpha/lifesize.cloud-0.1.10-alpha-ia32-full.nupkg
2016-04-04 17:04:03> UpdateInfo: Couldn't get release notes for:lifesize.cloud-0.1.10-alpha-ia32-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\dpereira\AppData\Local\lifesize\packages\lifesize.cloud-0.1.10-alpha-ia32-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
2016-04-04 17:04:04> Program: Starting Squirrel Updater: --update http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:04:04> Program: Starting update, downloading from http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:04:04> Program: About to update to: C:\Users\dpereira\AppData\Local\lifesize
2016-04-04 17:04:04> CheckForUpdateImpl: Downloading RELEASES file from http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha
2016-04-04 17:04:04> FileDownloader: Downloading url: http://lsnuts-dev.us-east-1.elasticbeanstalk.com/update/win32/0.1.9-alpha/RELEASES?id=lifesize&localVersion=0.1.9-alpha-ia32&arch=amd64
2016-04-04 17:04:04> FileDownloader: Downloading file: http://lsnuts-dev.us-east-1.elasticbeanstalk.com/download/0.1.10-alpha/lifesize.cloud-0.1.10-alpha-ia32-full.nupkg
2016-04-04 17:05:13> ApplyReleasesImpl: Writing files to app directory: 
... Here things go as planned ...
```

**Comment by djpereira** [comment]
Turns out this caused by a different issue (see https://github.com/electron/electron/issues/5057).
