### ISSUE TITLE
build with remoteReleases

### ISSUE THREAD

**Issue by gggin** [electron/windows-installer#87]
```json
{"win": {
      "remoteReleases": "http://sdfdsfdsfdsf/update/win64/1.0.3/stable"
    }}
```

with electron-release-server

npm 3.8.6
node 6.0.0
error:

Packaging app for platform win32 x64 using electron v0.37.8
Attemping to sync URL as remote RELEASES folder
Error: G:\dfg\dfg\node_modules\electron-winstaller-fixed\vendor\Updat
e.com failed with exit code: 4294967295
    at ChildProcess.proc.on.code (G:\dfg\dfg\node_modules\electron-wi
nstaller-fixed\lib\spawn-promise.js:33:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (G:\dfg\dfg\node_modules\electron-winstaller-fixed\lib\s
pawn-promise.js:22:10)
    at G:\dfg\dfg\node_modules\electron-winstaller-fixed\lib\index.js
:168:38
    at undefined.next (native)
From previous event:
    at releasify (G:\dfg\dfg\node_modules\electron-winstaller-fixed\l
ib\index.js:171:16)
    at Object.<anonymous> (G:\dfg\dfg\node_modules\electron-winstalle
r-fixed\lib\index.js:94:11)
From previous event:
    at Object.createWindowsInstaller (G:\dfg\dfg\node_modules\electro
n-winstaller-fixed\lib\index.js:118:16)
    at WinPackager.<anonymous> (G:\dfg\dfg\node_modules\electron-buil
der\src\winPackager.ts:161:48)
    at undefined.next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (G:\dfg\dfg\node_modules\electron-builder\src\awaite
r.ts:10:47)
    at Object.build (G:\dfg\dfg\node_modules\electron-builder\src\bui
lder.ts:30:59)
    at Object.<anonymous> (G:\dfg\dfg\node_modules\electron-builder\s
rc\build-cli.ts:47:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)

**Comment by develar** [comment]
electron-builder uses forked version of windows-installer, it is better to file issue to electron-buidler issues at first. Please try to use version 3.20.0.

**Comment by MarshallOfSound** [comment]
`remoteReleases` is expected to be a Github repository I believe

**Comment by gggin** [comment]
update electron-builder will be good
remoteReleases can be electron-release-server

**Comment by b-zurg** [comment]
For anyone else looking at this in the future I was able to set `remoteReleases` to my github repo without a trailing forward slash and it worked fine. 

e.g. `https://github.com/b-zurg/myapp`
