### ISSUE TITLE
Invalid URI error?!

### ISSUE THREAD

**Issue by arthurscheeren** [electron/windows-installer#90]
electron-installer-windows --src release/win32-x64/app-win32-x64 --dest dist/installers/  --options.version 0.1
  
Creating package (this may take a while)
[Error: Error creating package: Error executing file (1):
 ``` 

electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\\AppData\Local\Temp\electron-116418-7308-13rc54g\app_0.1\nuget\xcheque-dev-tools.nuspec -BasePath C:\Users\user\AppData\Local\Temp\electron-116418-7308-13rc54g\app_0.1\app -OutputDirectory C:\Users\scheeren\AppData\Local\Temp\electron-116418-7308-13rc54g\xcheque-dev-tools_0.1\nuget -NoDefaultExcludes
Invalid URI: The format of the URI could not be determined.
] 'Error: Error creating package: Error executing file (1):   \\nuget -NoDefaultExcludes\nInvalid URI: The format of the URI could not be determined.\r\n\n    at D:\\Projects\\app\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (D:\\Projects\\app\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:817:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)'

```

under app-win32-x64 folder i have the .exe, the dlls, the resources folder with the app.asar file inside

**Comment by MarshallOfSound** [comment]
I know this issue is old, but this is totally the wrong repository for this issue.

You appear to be using `electron-installer-windows` which can be found here https://github.com/unindented/electron-installer-windows
